// src/app/projects/page.tsx
import Link from "next/link";
import { vscodeProjects, personalProjects } from "@/data/projects";
import ProjectCard from "@/components/ProjectCard";

export const metadata = {
    title: "All Projects | Portfolio",
    description: "Browse all my projects and work.",
};

export default function ProjectsPage() {
    return (
        <main className="px-6 pb-24 pt-28">
            <div className="mx-auto max-w-6xl">
                <div className="mb-12">
                    <Link
                        href="/"
                        className="text-sm font-medium text-purple-600 transition-colors hover:text-purple-800 dark:text-purple-400 dark:hover:text-purple-300"
                    >
                        &larr; Back to Home
                    </Link>
                </div>

                <h1 className="mb-4 text-4xl font-bold tracking-tight text-zinc-900 dark:text-white">
                    All Projects
                </h1>
                <p className="mb-16 text-zinc-600 dark:text-zinc-400">
                    A collection of all my work and side projects.
                </p>

                {/* VS Code Work */}
                <h2 className="mb-2 text-2xl font-bold tracking-tight text-zinc-900 dark:text-white">
                    VS Code Work
                </h2>
                <div className="mx-auto mb-8 h-1 w-12 rounded bg-purple-600 mr-auto ml-0" />
                <div className="mb-20 grid gap-8 md:grid-cols-2">
                    {vscodeProjects.map((project) => (
                        <ProjectCard key={project.title} project={project} />
                    ))}
                </div>

                {/* Personal Work */}
                <h2 className="mb-2 text-2xl font-bold tracking-tight text-zinc-900 dark:text-white">
                    Personal Work
                </h2>
                <div className="mx-auto mb-8 h-1 w-12 rounded bg-purple-600 mr-auto ml-0" />
                <div className="grid gap-8 md:grid-cols-2">
                    {personalProjects.map((project) => (
                        <ProjectCard key={project.title} project={project} />
                    ))}
                </div>
            </div>
        </main>
    );
}

// src/routes/projects/+page.svelte
<script lang="ts">
	import { vscodeProjects, personalProjects } from '$lib/data/projects';
	import ProjectCard from '$lib/components/ProjectCard.svelte';
</script>

<svelte:head>
	<title>All Projects | Portfolio</title>
	<meta name="description" content="Browse all my projects and work." />
</svelte:head>

<main class="px-6 pb-24 pt-28">
	<div class="mx-auto max-w-6xl">
		<div class="mb-12">
			<a
				href="/"
				class="text-sm font-medium text-purple-600 transition-colors hover:text-purple-800 dark:text-purple-400 dark:hover:text-purple-300"
			>
				&larr; Back to Home
			</a>
		</div>

		<h1 class="mb-4 text-4xl font-bold tracking-tight text-zinc-900 dark:text-white">
			All Projects
		</h1>
		<p class="mb-16 text-zinc-600 dark:text-zinc-400">
			A collection of all my work and side projects.
		</p>

		<!-- VS Code Work -->
		<h2 class="mb-2 text-2xl font-bold tracking-tight text-zinc-900 dark:text-white">
			VS Code Work
		</h2>
		<div class="mx-auto mb-8 ml-0 mr-auto h-1 w-12 rounded bg-purple-600"></div>
		<div class="mb-20 grid gap-8 md:grid-cols-2">
			{#each vscodeProjects as project}
				<ProjectCard {project} />
			{/each}
		</div>

		<!-- Personal Work -->
		<h2 class="mb-2 text-2xl font-bold tracking-tight text-zinc-900 dark:text-white">
			Personal Work
		</h2>
		<div class="mx-auto mb-8 ml-0 mr-auto h-1 w-12 rounded bg-purple-600"></div>
		<div class="grid gap-8 md:grid-cols-2">
			{#each personalProjects as project}
				<ProjectCard {project} />
			{/each}
		</div>
	</div>
</main>
