// src/components/Footer.tsx
export default function Footer() {
    return (
        <footer className="border-t border-purple-200/50 px-6 py-8 dark:border-purple-900/50">
            <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 sm:flex-row">
                <p className="text-sm text-zinc-600 dark:text-zinc-400">
                    &copy; {new Date().getFullYear()} Your Name. All rights reserved.
                </p>
                <div className="flex gap-6">
                    <a
                        href="https://github.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
                    >
                        GitHub
                    </a>
                    <a
                        href="https://linkedin.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
                    >
                        LinkedIn
                    </a>
                    <a
                        href="https://twitter.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
                    >
                        Twitter
                    </a>
                </div>
            </div>
        </footer>
    );
}

// src/lib/components/Footer.svelte
<footer class="border-t border-purple-200/50 px-6 py-8 dark:border-purple-900/50">
	<div
		class="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 sm:flex-row"
	>
		<p class="text-sm text-zinc-600 dark:text-zinc-400">
			&copy; {new Date().getFullYear()} Your Name. All rights reserved.
		</p>
		<div class="flex gap-6">
			<a
				href="https://github.com"
				target="_blank"
				rel="noopener noreferrer"
				class="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
			>
				GitHub
			</a>
			<a
				href="https://linkedin.com"
				target="_blank"
				rel="noopener noreferrer"
				class="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
			>
				LinkedIn
			</a>
			<a
				href="https://twitter.com"
				target="_blank"
				rel="noopener noreferrer"
				class="text-sm text-zinc-600 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
			>
				Twitter
			</a>
		</div>
	</div>
</footer>
